//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TercerParcial_Ortiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagina
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CantidadLikes { get; set; }
        public string Categoria { get; set; }
        public string Ciudad { get; set; }
    }
}
