//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TercerParcial_Ortiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publicacion
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Mes { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
    }
}
